#+PROPERTY: header-args:bash :results verbatim

* dotfiles

  Configuration files for my personal setup.
  

** System requirements
   
*** MacOS - [[file:homebrew/README.org][file:homebrew/README.org]]

    I work mostly on a MacOS system, so this is the system with the
    most customisations.
    
*** Debian - [[id:4990c70f-908a-4f33-adcd-c8c815aacf73][Debian from scratch]]

    I used to work a lot in Debian but now I find it hard to justify
    maintaining two systems, so this is here mostly for those cases
    where I need to setup a Debian/Linux system in case my main system
    is not usable.

    
** Configure Emacs [[file:emacs/README.org]]

   Emacs is my main editor, so a fundamental part of the setup.
   

** Configure Bash: [[file:bash/README.org][file:bash/README.org]]

   I use Bash as my default shell.


** Program-specific instructions

   I have collected various configuration files for different
   programs, however, they are not as fundamental as the ones
   highlighted above:
   
   #+begin_src bash :exports results :results output table
     for d in $(find . -not -name ".*" -type d -maxdepth 1 | sort);
     do
         README="${d}/README.org"
         if [ ! -f ${README} ]; then
            echo "${README} [MISSING]"
            continue
         fi

        echo "[[${README}][${README}]]"
     done
   #+end_src

   #+RESULTS:
   | [[file:./bash/README.org][./bash/README.org]]     |           |
   | ./beets/README.org    | [MISSING] |
   | [[file:./debian/README.org][./debian/README.org]]   |           |
   | [[file:./emacs/README.org][./emacs/README.org]]    |           |
   | [[file:./git/README.org][./git/README.org]]      |           |
   | [[file:./gpg/README.org][./gpg/README.org]]      |           |
   | [[file:./homebrew/README.org][./homebrew/README.org]] |           |
   | ./iterm/README.org    | [MISSING] |
   | [[file:./mc/README.org][./mc/README.org]]       |           |
   | ./mpd/README.org      | [MISSING] |
   | [[file:./ncmpcpp/README.org][./ncmpcpp/README.org]]  |           |
   | [[file:./tmux/README.org][./tmux/README.org]]     |           |
   | ./xdotool/README.org  | [MISSING] |


** Updating all code block results

   Run all code blocks: =C-c C-v C-b=

