;;-*-coding: utf-8;-*-
(define-abbrev-table 'global-abbrev-table
  '(
    ("Abbrev" "Abbreviations" nil :count 8)
    ("abbrev" "abbreviation" nil :count 6)
    ("abbrevs" "abbreviations" nil :count 3)
    ("ae" "ä" nil :count 3)
    ("dep" "dependency" nil :count 1)
    ("ebo" "exponential backoff: x->y days" nil :count 2)
    ("ema" "Emacs" nil :count 6)
    ("lett" "let the" nil :count 2)
    ("md" "Markdown" nil :count 1)
    ("n26is" ": N26: Income Sorter :n26:is:" nil :count 1)
    ("ncm" "Clara Marie" nil :count 2)
    ("nk" "Knetledge" nil :count 1)
    ("nogo" "not going to" nil :count 2)
    ("ntt" "new: task tracking" nil :count 19)
    ("smes" "subject-matter experts" nil :count 1)
    ("td" "Today" nil :count 2)
    ("tex" "LaTeX" nil :count 2)
    ("tfo" "to find out" nil :count 1)
    ("vllt" "vielleicht" nil :count 1)
    ("wtft" "was the first time" nil :count 2)
   ))

