;;; WARNING: Do NOT edit this file by hand.
;; Instead edit the Org file and regenerate this
;; elisp script using: org-babel-tangle (C-c C-v t)

(require 'pgpb-packages)

(require 'pgpb-helpers)

(pgpb-install-packages)
(pgpb-ignore-custom-file)
(pgpb-auto-dim-buffers)
(pgpb-customize-vars)
(pgpb-javascript)
(pgpb-latex-opts)
(pgpb-autosave)
(pgpb-flyspell)
(pgpb-magit)
(pgpb-customize-appearance)
(pgpb-global-keys)

(require 'init-helm-projectile)

(require 'pgpb-org)

(require 'pgpb-docker)

(when (eq system-type 'darwin)
  (require 'pgpb-macos)
  )

(when (eq system-type 'gnu/linux)
  (message "Inside a Linux system")
  (use-package pinentry
    :ensure t
    :config
    (pinentry-start)
    )

  ;;; My system uses =lp= instead of =lpr=
  ;; https://stackoverflow.com/questions/28765952/emacs-printing-error-unknown-option-j
  (setq lpr-command "lp"
        lpr-add-switches nil)
  (message "Linux-specific options set"))

(when (eq system-type 'windows-nt)
  (require 'pgpb-win10)
  (require 'pgpb-wsl)
  )

(require 'pgpb-blog)

(require 'pgpb-abbrev)

(require 'pgpb-test)

(require 'pgpb-llm)

(provide 'pgpb)
