;;; WARNING: Do NOT edit this file.
;; This file is generated from the Org file via =org-tangle=

(setq daily-tags '("+daily" "-private" "-template"))

(setq org-agenda-hide-tags-regexp
      (regexp-opt '("goal"
                    "task"
                    "action"
                    "hobby"
                    "PROJECT"
                    "reminder"
                    "recurring"
                    "time"
                    "info"
                    "journal"
                    "track"
                    "termin"
                    "bookmark")))

(setq hidden "-info-journal/-INFO-DONE-WONTDO-IGNORE")

(defun pgpb-org-daily ()
  '("d" "Daily checklist"
    ((agenda ""))
    ((org-agenda-tag-filter-preset daily-tags))
    ))

(defun pgpb-org-public-tasks ()
  '("k" "Public tasks"
    ((agenda ""))
    ((org-agenda-tag-filter-preset '("-daily" "-improve" "-private" "-template")))
    ))

(defun pgpb-org-time ()
       '("f" "Time tracking" tags (concat "+time+track" hidden)))

(defun pgpb-org-now ()
  ;; Filter by priority
  ;; https://emacs-orgmode.gnu.narkive.com/bsur8gfw/orgmode-custom-agenda-view-filter-by-priority-and-scheduled-date
  '("n" "Now! a.k.a. Prio=A"
    ((agenda ""))
    ((org-agenda-skip-function '(org-agenda-skip-entry-if 'notregexp "\\[#A\\]")))
    ))

(defun pgpb-org-all ()
  '("l" "All tasks"
    ((agenda ""))
    ((org-agenda-tag-filter-preset '("-daily" "-improve" "-template")))
    ))

(defun pgpb-org-meetings ()
  '("j" "All meetings"
    ((agenda ""))
    ((org-agenda-tag-filter-preset '("+termin" "-template")))
    ))

(defun pgpb-org-find ()
       '(("F" . "Find/Search")
         ("Fj" "Journal search" search ""
          ((org-agenda-files (pgpb-org-journal-files))))
         ("Fa" "Archive search" search ""
          ((org-agenda-files (pgpb-org-archive-files))))
         ("Fe" "Search everywhere" search ""
          ((org-agenda-text-search-extra-files (pgpb-org-extra-files))))))

(defun pgpb-org-goals ()
  ;; See Org etry: =C-c h goals task action=
  ;; (org-id-goto "E5B8D3A5-66EF-45A2-BB21-BADDC147650A")
  '(("g" . "Goals, Hobbies and Dreams")
    ("gg" "Goal definition" tags (concat "+goal+def"))
    ("gh" "Hobbies" tags (concat "+hobby+def"))
    ("gd" "Dreams" tags "+dream+def")
    ;; Items that are not associated to any goal/hobby
    ;; (org-id-goto "A753CCF1-D6DF-47CF-BF16-067BD937E30A")
    ("gz" "Dangling/Zombie items" tags (concat "-pom-fit-de-blog-meta-job" "-hobby" hidden))))

(defun pgpb-org-reminder ()
       '(("R" . "Reminders")
         ("Rd" "Daily reminders"
          ((agenda ""))
          ((org-agenda-tag-filter-preset daily-tags))
          )
         ("Ra" "All Reminders"
          ((agenda ""))
          ((org-agenda-tag-filter-preset '("+reminder" "-template")))
          )
         ("Ro" "Other Reminders"
          ((agenda ""))
          ((org-agenda-tag-filter-preset '("+reminder" "-template" "-daily")))
          )))

(defun pgpb-org-ooo ()
   '(("O" . "Out of Office")
     ("Om" "Monthly view"
      ((agenda ""))
      ((org-agenda-span 'month)
       (org-agenda-tag-filter-preset '("+ooo")))
      )
     ("Oa" "All events" tags "+ooo/-INFO")))

(defun pgpb-org-improve ()
  '(("I" . "Improvements")
    ("Ib" "Backlog" tags "+improve-info/-DONE-INFO-WONTDO")
    ("Iw" "work in progress"
     ((agenda ""))
     ((org-agenda-tag-filter-preset '("+improve")))
     )))

(setq org-agenda-custom-commands 
      (append (list
               (pgpb-org-public-tasks)
               (pgpb-org-all)
               (pgpb-org-daily)
               (pgpb-org-time)
               (pgpb-org-now)
               (pgpb-org-meetings))
              (pgpb-org-find)
              (pgpb-org-goals)
              (pgpb-org-reminder)
              (pgpb-org-ooo)))

(provide 'pgpb-org-agenda-commands)
