;;; WARNING: Do NOT edit this file.
;; This file is generated from the Org file via =org-tangle= 
(message "early-init: pgpb")

(defvar pgpb-gpg-keys (list "pgpb.padilla@gmail.com")
  "GPG recipient to use for encrypting Org files.")

(defvar pgpb-agenda-dir "~/org/31e520d4df"
  "Directory for files that will be used to build the Org agenda.")
(defvar pgpb-journal-dir "~/org/0f6de25076"
  "Directory for my Journal files. Not used to build the agenda.")
(defvar pgpb-archive-dir "~/org/2204c36fc7"
  "Directory for Archived files. Not used to build the agenda.")
