;;; WARNING: Do NOT edit this file.
;; This file is generated from the Org file via =org-tangle= 
(message "early-init: pgpb")

(defvar pgpb-gpg-keyid "49D11CD0A2D09F63"
  "GPG key ID to use for encrypting Org files.")

(defvar pgpb-org-agenda-dir "~/org/31e520d4df"
  "Directory for files that are used to build the Org agenda.")
(defvar pgpb-org-journal-dir "~/org/0f6de25076"
  "Directory for my Journal files. Not used to build the agenda.")
(defvar pgpb-org-archive-dir "~/org/2204c36fc7"
  "Directory for Archived files. Not used to build the agenda.")
