;;; WARNING: Do NOT edit this file.
;; This file is generated from the Org file via =org-tangle=

(dolist (i (list (concat user-emacs-directory "pgpb")))
  ;; Add all at end of `load-path' to avoid conflicts.
  (add-to-list 'load-path (file-name-as-directory i) t))

(require 'pgpb)
(require 'weak-pinky)
(require 'pgpb-extras)
