;;; WARNING: Do NOT edit this file by hand.
;; Instead edit the Org file and regenerate this
;; elisp script using: org-babel-tangle (C-c C-v t)

(defvar my-org-agenda-dir 
  "~/org/31e520d4df"
  "Directory for Agenda files.")

(defvar my-org-journal-dir
  "~/org/0f6de25076"
  "Directory for Journal files.")

(defvar my-org-archive-dir
  "~/org/2204c36fc7"
  "Directory for Archive files.")

(defun my-org-dirs ()
  "List special Org directories."
  (interactive)
  (cl-loop for symbol being the symbols
           when (and (boundp symbol)
                     (string-match-p "my-org-.*-dir" (symbol-name symbol)))
           collect symbol))

(provide 'my-org-files)
