;;; WARNING: Do NOT edit this file by hand.
;; Instead edit the Org file and regenerate this
;; elisp script using: org-babel-tangle (C-c C-v t)

(defun my-org-dirs ()
  "List special Org directories."
  (interactive)
  (cl-loop for symbol being the symbols
           when (and (boundp symbol)
                     (string-match-p "my-org-.*-dir" (symbol-name symbol)))
           collect symbol))
