;;; WARNING: Do NOT edit this file by hand.
;; Instead edit the Org file and regenerate this
;; elisp script using: org-babel-tangle (C-c C-v t)

(require 'pgpb-packages)
(require 'pgpb-helpers)

(pgpb-install-packages)
(pgpb-ignore-custom-file)
(pgpb-auto-dim-buffers)
(pgpb-customize-vars)
(pgpb-javascript)
(pgpb-latex-opts)
(pgpb-autosave)
(pgpb-flyspell)
(pgpb-magit)
(pgpb-customize-appearance)
(pgpb-linux-hacks)
(pgpb-global-keys)

;;; Load Windows customizations
(when (eq system-type 'windows-nt)
  (load-relative "./win10.el")
  (load-relative "./wsl.el")
  (message "Ok: windows hacks loaded.")
  )

;;; Darwin (MacOS) customizations
(when (eq system-type 'darwin)
  (load-relative "./darwin.el")
  (message "Ok: macos hacks loaded.")
  )

(load-relative "./abbrev.el")

;;; Helm stuff
(require 'init-helm-projectile)

;;; Org Mode
(require 'pgpb-org)
(pgpb-org-main pgpb-gpg-keys
               pgpb-org-dirs)


(require 'pgpb-docker)

(provide 'pgpb)
