#+PROPERTY: header-args:bash :results verbatim

* Emacs configuration

  Given that Emacs is already installed, then you can proceed to apply
  the customisations described in this section.
  

** System requirements

   All Emacs packages are installed during the initial load of the
   init file.

   However, there are a few steps required to ensure that Emacs works
   as expected.
   

*** Encrypting Org files with GnuPG - [[https://gnupg.org/][gnupg.org]]

    Required to [en|de]crypt Org files as described in
    [[https://orgmode.org/worg/org-tutorials/encrypting-files.html][Org tutorial: Encrypting files]].

    
**** Install GnuPG


***** MacOS: Install with [[file:~/dotfiles/homebrew/README.org][Brewfile]]

      For MacOS, GnuPG can be installed using [[id:8BD78C5A-802B-4E9E-8484-D2E5E259574B][Homebrew]]:
     
      #+begin_src bash
        ack gnupg ../homebrew
      #+end_src

      #+RESULTS:
      : ../homebrew/Brewfile.core:14:brew "gnupg@2.2.41"

     
***** Debian: Install via system package manager

      For debian there's nothing special, simply use the system's
      package manager.


**** Configure GnuPG
     
     *WARN*: Additional configuration needs to be installed, see:
     [[file:~/dotfiles/gpg/README.org::#macos-gpg-config][file:~/dotfiles/gpg/README.org::#macos-gpg-config]]

      
*** Initialize git submodules

    My customisations make use of some git submodules:

    #+begin_src bash
      git submodule
    #+end_src

    #+RESULTS:
    :  40cc1ac76d741055cbefa13860d9f070a7ade001 org-yt (40cc1ac)

    You should initialise so that everything works fine:

    #+begin_src bash 
      git submodule update --init
    #+end_src

    #+RESULTS:

    
** Install Emacs customisations

   You can download this repository anywhere in your computer, so long
   as you tell Emacs to use the correct user directory. The correct
   directory is the one containing the file you are currently reading.

   Current working directory:

   #+begin_src elisp
     default-directory
   #+end_src

   #+RESULTS:
   : /Users/pgpb.padilla/code/dotfiles-experimental/emacs/


   Emacs User directory:
   
   #+begin_src elisp
     user-emacs-directory
   #+end_src

   #+RESULTS:
   : /Users/pgpb.padilla/code/dotfiles-experimental/emacs/


** Related links

   1. You can read more about the Emacs user directory using the help
      function: =C-h v emacs-user-directory=:
      
      #+begin_src elisp :results output
        (describe-variable 'user-emacs-directory)
      #+end_src

      #+RESULTS:
      
   2. Location of the Emacs init files.
      It might differ, depending on the base system. See: [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Find-Init.html][Find Init]].
  
  
