#+PROPERTY: header-args:bash :results verbatim

* Emacs configuration

** System requirements

   Most Emacs packages are installed during the initial load of the
   init file. However, there are dependencies to system binaries:


*** Initialize git submodules

    #+begin_src bash 
      git submodule update --init
    #+end_src

    #+RESULTS:

    
*** GnuPG: Encrypting Org files - [[https://orgmode.org/worg/org-tutorials/encrypting-files.html][orgmode.org]]

    The [[https://www.emacswiki.org/emacs/EasyPG][EasyPG]] Emacs package requires the =gpg= binary to be installed
    and also be in the system =PATH=.

    This is because the Emacs configuration explicitly uses the =gpg=
    binary instead of its absolute path:
    
    #+begin_src bash
      ack -C 1 gpg-program *.el
    #+end_src

    #+RESULTS:
    : pgpb-org.el-8-(require 'epg)
    : pgpb-org.el:9:(setq epg-gpg-program "gpg"
    : pgpb-org.el-10-      epg-pinentry-mode 'loopback)


**** Installing GnuPG - [[https://gnupg.org/][gnupg.org]]
     
***** MacOS - [[file:~/dotfiles/homebrew/README.org::#brewfile-core][Homebrew (core)]]
     
      =gpg= can be installed via [[file:~/dotfiles/homebrew/README.org::#brewfile-core][Homebrew (core)]]:

      #+begin_src bash
        grep gnupg ../homebrew/Brewfile.core
      #+end_src

      #+RESULTS:
      : brew "gnupg@2.2"

      *WARN*: Additional configuration needs to be installed, see:
      [[file:~/dotfiles/gpg/README.org::#macos-gpg-config][file:~/dotfiles/gpg/README.org::#macos-gpg-config]]

      
***** Debian

      checkout [[https://packages.debian.org/en/sid/apt-clone][apt-clone]]



** Installation

*** Backup config
    :LOGBOOK:
    CLOCK: [2024-01-31 Mi 20:56]--[2024-01-31 Mi 21:21] =>  0:25
    :END:

    Review current init scripts and backup any important information. 

    Are those files symlinks?
    
    #+begin_src bash :dir ~/
      tree -a -L 1 . | grep emacs
    #+end_src

    #+RESULTS:
    : ├── .emacs.d
    : ├── .emacs.keyfreq


    Related:

    1. Location of the Emacs init files.
       It might differ, depending on the base system. See: [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Find-Init.html][Find Init]].
  
  
*** Install emacs directory

    #+begin_src bash :dir ~/
      rm -rf ~/.emacs.d
      ln -sfv  ~/dotfiles/emacs/ ~/.emacs.d
    #+end_src

    #+RESULTS:
    : /Users/pgpb.padilla/.emacs.d -> /Users/pgpb.padilla/dotfiles/emacs/
